- files/usr/lib/systemd/system/jeos-firstboot.service
Use default.target to run regardless of the runlevel.
> Add [Install] section to jeos-firstboot.service

- files/usr/lib/systemd/system/jeos-firstboot.service
Fixes cycle on sysinit.service
Needs some testing to verify that the correct font is always loaded.
> Use same dependencies as systemd-firstboot.service

- files/usr/lib/jeos-firstboot
Making it 'auto' to match leanOS default install and removing the DHCLIENT_SET_HOSTNAME option because of the clash with other config files, described in the bug.
> Change default values for ifcfg files bsc#1069782

- files/usr/lib/jeos-firstboot
> Turn off systemd status output while jeos-firstboot is running

- files/usr/lib/jeos-firstboot
- files/usr/lib/systemd/system/jeos-firstboot.service
Use live-langset-data.
This required a rewiring of the jeos-firstboot.service so I also changed the way it's enabled to fix a different bug.
> Refine locale setup again

- files/usr/lib/jeos-firstboot
- Only the locales langset knows about can be chosen anyway
- Fixes bsc#1104041
> Get list of locales from /usr/share/langset/ and remove duplicate "us" keymap

- files/usr/lib/jeos-firstboot
While openSUSE changed the main location for license files to the standard RPM
license directory /usr/share/licenses/$packagename/, SLE did it in an
incompatible way that requires indirection to get to it.
Works around jsc#SLE-3067 and fixes bsc#1127166
> Support the non-standard and hopefully temporary location for the SLE EULAs

- files/usr/lib/jeos-firstboot
As sometime people who build images don't use BtrfFS and don't need snapper. Add checking before run snapper.
> Test if snapper exists before trying to run it

- files/usr/lib/jeos-firstboot
We were setting the msglevel to 4 instead of using
whatever was the current one
> reenable console loglevel to the default

- files/usr/lib/jeos-firstboot
This is to support running jeos-firstboot on a system with already
configured quota setup.
> Only configure snapper quota if no btrfs qgroups exist yet

- files/usr/lib/jeos-firstboot
- files/usr/share/jeos-firstboot/raspberrywifi
As in Issue #4 states: There should be way to execute external scripts. This is bit naive way to achieve that goal but should be enough for most cases.
> Execute external script(s) on firstboot

- files/usr/lib/jeos-firstboot
- files/usr/share/defaults/jeos-firstboot.conf
Add two new variables to jeos-firstboot:
* `TIMEZONE_PRESET`
Based on `LOCALE_PRESET` and `KEYTABLE_PRESET`, this new variable will affect the `systemd_firstboot_args` array if is set, and will skip the time-zone dialog.
* `PASSWORD_ALREADY_SET`
If set to a non-zero value, will skip the root password dialog. Is expected that the user is setting the root password via other means, like `config.sh` or the Kiwi `users` XML tag.
Also fix the call of btrfs on non-btrfs file systems.
> Allows the skip of timezone and password dialogs

- files/usr/lib/jeos-firstboot
- files/usr/lib/jeos-firstboot-functions
* Configure all interfaces where DHCP answer
* Fix grep stderr output in is_raspberry that happens in non-rpi devices
> Add JEOS_MULTINET configuration option

- files/usr/lib/jeos-firstboot
In non-UEFI JeOS images not always /etc/sysconfig/bootloader is
present. When this system is missing, jeos-firstboot service fail
and shutdown the full machine.
> Do not fail when updating bootloader in no-UEFI

- files/usr/lib/systemd/system/jeos-firstboot-snapshot.service
Failed in weird ways in openQA, "multi-user.target not reached" without any hint as to why.
With this it appears to work, at least once.
> Run jeos-firstboot-snapshot after local-fs and ignore systemd-user-sessions

- files/usr/lib/jeos-firstboot
In openSUSE based distributions we do not want to show the SUSEConnect dialog when this package is available, as the updates are not related with registration.
For installation media, installing SUSEConnect in openSUSE will make sense.
> SUSEConnect: do not show the register dialog on non-SLE distributions

- files/usr/lib/jeos-firstboot
The variables were not exported, so not visible to the nested instance.
> Fix skipping duplicate locale and keyboard layout dialogs

- files/usr/lib/jeos-firstboot
- files/usr/share/defaults/jeos-firstboot.conf
We could need to create images that leverage jeos-firstboot to take care
of locale / keyboard or network configuration, and where the image is
already part of a different product.  For example, a PXE boot image
(installed via RPM), that will be used as a component to provisioning
new images in a network.
This use case will require no user interaction during the boot process,
and currently there is a dialog that forces the user to accept the EULA
license.
This patch add a new option, JEOS_EULA_ALREADY_AGREED, that if set to a
nonempty value, will skip the dialog showed for EULA acceptance. As
commented in the example configuration file, this option is expected to
be used only when the image is part of a different product that contains
an already accepted license.
Fix #63
> Add JEOS_EULA_ALREADY_AGREED option

- files/usr/lib/jeos-firstboot
- files/usr/share/defaults/jeos-firstboot.conf
In SLE based images where SUSEConnect is available, a dialog is shown to
the user to remember the registration of the product in order to fetch
future updates.
This commit add a new option that, if enabled, will hide the dialog and
avoid this user interaction.
Fix #65
> Add JEOS_HIDE_SUSECONNECT option

- files/usr/sbin/jeos-firstboot
This belongs in the documentation instead, which saves one mandatory
interaction on the first boot.
> Drop the info dialog about glibc-locale (jsc#SLE-15348)

- files/usr/sbin/jeos-firstboot
Only available in 246+, so keep a fallback.
Not really tested yet.
> Use race-free DBus API to silence systemd

- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
It's unnecessary and causes wicked to write an error into the journal.
> Skip the lo interface when probing for DHCP

- files/usr/sbin/jeos-firstboot
Alternative to https://github.com/openSUSE/jeos-firstboot/pull/84.
Intentionally not mentioning boo#1192940 because this just removes already unused code...
> Drop call to snapper setup-quota, kiwi does that meanwhile

- files/usr/lib/systemd/system/jeos-firstboot.service
- files/usr/sbin/jeos-firstboot
- files/usr/share/defaults/jeos-firstboot.conf
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
- files/usr/share/jeos-firstboot/welcome-screen
Currently, jeos-firstboot is only on the active console, which can only be
configured by changing the kernel cmdline. This commit introduces a welcome
dialog which is shown on all active consoles (from /proc/consoles) and it
continues on the console where the welcome screen was accepted.
~WIP because:~
> Introduce welcome screen for console switching

- files/usr/share/jeos-firstboot/welcome-screen
Currently it starts dialog for all consoles listed in /proc/consoles, but
some of them might not be working (e.g. not set up, see also bsc#1175514#c26).
When dialog is used on one of those consoles, it attempts to use stderr first
and if even that fails, /dev/tty. As a result, starting dialog on a broken
console causes a conflict with dialog on a working console, and weird behaviour
occurs.
Use "stty size" to check whether the console is usable before starting dialog.
> Skip broken consoles (bsc#1195975)

- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
Don't run wicked specific code in jeos-firstboot and run "nmtui" in
jeos-config.
https://github.com/openSUSE/jeos-firstboot/pull/91 allows implementing that in a less ugly way.
> Quick'n'dirty NetworkManager support

- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
The warn function hardcoded the size and the values were too small for this
message, so the important part was cut off and only visible through scrolling.
Fix that by always using automatic size.
The other warning dialogs look a bit odd now (not quite wide enough), but it's readable and they should never show up anyway...
> Fix size of the "No root password set" dialog

- files/usr/lib/systemd/system/jeos-firstboot.service
- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
- files/usr/share/jeos-firstboot/modules/network
- files/usr/share/jeos-firstboot/modules/network-modules/NetworkManager
- files/usr/share/jeos-firstboot/modules/network-modules/wicked
Add an abstraction for network configuration modules.
So far completely untested.
> Proper NetworkManager support

- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
See individual commits for details.
I suggest we make a branch `v1.1.x` for SLE 15 SP4(+) before merging this.
> Improve the "d" function

- LICENSE
- files/usr/lib/systemd/system/jeos-firstboot-snapshot.service
- files/usr/lib/systemd/system/jeos-firstboot.service
- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/sbin/jeos-firstboot-snapshot
- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
- files/usr/share/jeos-firstboot/modules/network
- files/usr/share/jeos-firstboot/modules/network-modules/NetworkManager
- files/usr/share/jeos-firstboot/modules/network-modules/wicked
- files/usr/share/jeos-firstboot/modules/raspberrywifi
- files/usr/share/jeos-firstboot/welcome-screen
Replace license headers and copyright strings with SPDX lines.
Fixes #93
Untested.
> Make use of SPDX identifiers

- files/usr/share/jeos-firstboot/modules/raspberrywifi
Don't show ESSIDs multiple times just because there are multiple APs transmitting this ESSID.
https://bugzilla.suse.com/show_bug.cgi?id=1197487
Please submit this change for 15sp4.
> Deduplicate wifi list

- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
Move reading os-release to jeos-firstboot-function and use /usr/lib/os-release if /etc/os-release is not available.
> Support /usr/lib/os-release (#102)

- files/usr/sbin/jeos-firstboot
That's not our job, it's handled by different services. With systemd v254 this option results in a fatal error.
> Don't pass --setup-machine-id to systemd-firstboot

- files/usr/lib/systemd/system/jeos-firstboot.service
In case the initrd puts keys in the kernel keyring, e.g. for disk encryption the firstboot wizard may want to access them.
> Add KeyringMode=shared

- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
- files/usr/share/jeos-firstboot/modules/network
- files/usr/share/jeos-firstboot/modules/network-modules/NetworkManager
- files/usr/share/jeos-firstboot/modules/network-modules/wicked
- files/usr/share/jeos-firstboot/modules/raspberrywifi
- files/usr/share/jeos-firstboot/welcome-screen
> Add support for shellcheck

- files/usr/share/jeos-firstboot/modules/status_mail
Depends on #97 
Draft because systemd-status-mail does not support SMTP auth yet.
> Add status_mail module for systemd-status-mail configuration

- files/usr/sbin/jeos-config
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
Instead of a single "d" function which tries to do everything, split it into
smaller pieces which can be used individually.
Fixes https://github.com/openSUSE/jeos-firstboot/issues/110
> Refactor dialog helpers in jeos-firstboot-functions

- files/usr/lib/systemd/system/jeos-firstboot.service
- files/usr/sbin/jeos-firstboot
There are cases in which ds-identify enables cloud-init but there isn't actually a data source. Check for that by reading a file in /run. It's not possible to express that as unit condition, so do it in code.
> Only skip jeos-firstboot if cloud-init found a config source (bsc#1220281)

- files/usr/lib/systemd/system/jeos-firstboot.service
cloud-init.target include cloud-init.service which needs to run after wicked. But this service wants to run prior to wicked. However, cloud-init knows what it shold be doing after the cloud-init-local phase and that service runs prior to wicked. As such the requirements from a systemd timing perspective are consistent.
> Resolve cycle w.r.t. wicked

- files/usr/sbin/jeos-firstboot
If there is only a single locale available on the system, the locale selection is skipped. In that case the timezone should default to UTC though, to avoid that for the common case of en_US it ends up as America/New_York.
This was the previous default by accident because live-langset-data used US/Eastern as TZ for en_US, but the timezone dialog does not handle aliases.
> Use UTC as default TZ if there was no locale selection dialog (boo#1224212)

- README
- README.md
- files/usr/sbin/jeos-config
- files/usr/sbin/jeos-firstboot
- files/usr/sbin/jeos-firstboot-snapshot
- files/usr/share/jeos-firstboot/jeos-firstboot-dialogs
- files/usr/share/jeos-firstboot/jeos-firstboot-functions
- files/usr/share/jeos-firstboot/modules/otp
- files/usr/share/jeos-firstboot/modules/raspberrywifi
- files/usr/share/jeos-firstboot/modules/user
Do some necessary cleanups + add some API for more flexibility with modules.
Add a basic module for user account creation:
Add a module for `pam_oath` configuration. It puts the configuration into the target user's `~/.pam_oath_usersfile`:
> Add modules for user creation and pam_oath configuration

- files/usr/share/jeos-firstboot/modules/otp
* otp: Use more obvious dd | base32 instead of tr | head
* otp: Use the system nodename as issuer in the QR code
> OTP module improvements

- files/usr/share/jeos-firstboot/modules/otp
If the screen is not tall enough to fit text + QR code simultaneously, add a button to show just the QR code.
> otp: Show the QR code in a separate window if necessary (bsc#1231177)
